In [1]:
import pandas as pd

from utils.apis import fetch_binance_btc
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from utils.utils import get_technical_indicators, create_target_column

In [2]:
# df = fetch_binance_btc('15m', 365 * 1 + 3)
# df.to_csv("../data/btc_1yrs.csv")

In [3]:
# df = fetch_binance_btc('15m', 365 * 5 + 3)
# df.to_csv("../data/btc_5yrs.csv")

In [4]:
# df = fetch_binance_btc('15m', 365 * 10 + 3)
# df.to_csv("../data/btc_10yrs.csv")

In [5]:
df_1y = pd.read_csv("../data/btc_1yrs.csv")
df_1y.set_index('timestamp', inplace=True)

df_5y = pd.read_csv("../data/btc_5yrs.csv")
df_5y.set_index('timestamp', inplace=True)

df_10y = pd.read_csv("../data/btc_10yrs.csv")
df_10y.set_index('timestamp', inplace=True)

In [6]:
get_technical_indicators(df_1y)
get_technical_indicators(df_5y)
get_technical_indicators(df_10y)

,open,high,low,close,volume,rsi_6,rsi_12,macd,macd_signal,macd_hist,...,strong_bullish_signal,strong_bearish_signal,higher_lows_3,lower_highs_3,trend_strength_bullish,trend_strength_bearish,distance_from_sma_pct,candle_body_pct,momentum_5,momentum_10
timestamp,,,,,,,,,,,,,,,,,,,,,
2017-08-17 21:00:00,4346.74,4367.93,4315.85,4367.93,10.556113,70.448703,58.043191,-13.462593,-24.016020,10.553427,...,3,1,False,False,0.970509,0.029491,-0.247818,0.406874,0.009872,0.030695
2017-08-17 21:15:00,4346.73,4369.69,4335.98,4349.33,18.736552,61.385237,54.148080,-9.825137,-21.177843,11.352706,...,3,2,True,False,0.799374,0.200626,-0.667439,0.077128,0.016662,0.021696
2017-08-17 21:30:00,4349.33,4369.69,4322.65,4354.35,13.210825,62.929843,55.036479,-6.462856,-18.234846,11.771990,...,4,1,False,False,0.803901,0.196099,-0.550223,0.106718,0.019000,0.016927
2017-08-17 21:45:00,4354.03,4368.68,4309.23,4333.55,19.269546,52.490243,50.604590,-5.414198,-15.670716,10.256518,...,3,2,False,False,0.671627,0.328373,-1.013319,0.344491,0.006632,0.010715
2017-08-17 22:00:00,4333.55,4349.63,4322.39,4334.32,11.280595,52.837803,50.764705,-4.469475,-13.430468,8.960993,...,3,1,False,False,0.681071,0.318929,-0.949489,0.028267,-0.002857,0.001634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-11-12 20:30:00,101717.30,101846.15,101621.08,101683.41,173.974830,56.461330,41.692748,-527.165091,-635.447993,108.282901,...,2,2,False,False,0.615778,0.384222,-1.648521,0.150575,0.005914,0.000145
2025-11-12 20:45:00,101683.41,101716.61,101487.81,101539.01,114.583150,47.977011,38.913150,-493.315446,-607.021483,113.706038,...,1,3,False,False,0.497395,0.502605,-1.744016,0.631119,0.001340,-0.000707
2025-11-12 21:00:00,101539.01,101897.99,101520.41,101894.32,95.287950,63.965460,48.185714,-432.829422,-572.183071,139.353649,...,2,2,False,False,0.898643,0.101357,-1.359008,0.941019,0.005894,0.003885
2025-11-12 21:15:00,101894.32,101894.33,101694.00,101715.78,87.972500,53.964756,44.484238,-394.750065,-536.696470,141.946405,...,2,2,False,False,0.694525,0.305475,-1.485470,0.891229,0.002798,0.001710
2025-11-12 21:30:00,101715.78,101864.54,101715.66,101864.31,79.703270,60.179851,48.102269,-348.568687,-499.070913,150.502226,...,2,2,True,False,0.849814,0.150186,-1.285480,0.997649,0.001445,0.006991

In [7]:
create_target_column(df_1y)
create_target_column(df_5y)
create_target_column(df_10y)

,open,high,low,close,volume,rsi_6,rsi_12,macd,macd_signal,macd_hist,...,strong_bearish_signal,higher_lows_3,lower_highs_3,trend_strength_bullish,trend_strength_bearish,distance_from_sma_pct,candle_body_pct,momentum_5,momentum_10,target
timestamp,,,,,,,,,,,,,,,,,,,,,
2017-08-17 21:00:00,4346.74,4367.93,4315.85,4367.93,10.556113,70.448703,58.043191,-13.462593,-24.016020,10.553427,...,1,False,False,0.970509,0.029491,-0.247818,0.406874,0.009872,0.030695,-1
2017-08-17 21:15:00,4346.73,4369.69,4335.98,4349.33,18.736552,61.385237,54.148080,-9.825137,-21.177843,11.352706,...,2,True,False,0.799374,0.200626,-0.667439,0.077128,0.016662,0.021696,-1
2017-08-17 21:30:00,4349.33,4369.69,4322.65,4354.35,13.210825,62.929843,55.036479,-6.462856,-18.234846,11.771990,...,1,False,False,0.803901,0.196099,-0.550223,0.106718,0.019000,0.016927,0
2017-08-17 21:45:00,4354.03,4368.68,4309.23,4333.55,19.269546,52.490243,50.604590,-5.414198,-15.670716,10.256518,...,2,False,False,0.671627,0.328373,-1.013319,0.344491,0.006632,0.010715,0
2017-08-17 22:00:00,4333.55,4349.63,4322.39,4334.32,11.280595,52.837803,50.764705,-4.469475,-13.430468,8.960993,...,1,False,False,0.681071,0.318929,-0.949489,0.028267,-0.002857,0.001634,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-11-12 20:30:00,101717.30,101846.15,101621.08,101683.41,173.974830,56.461330,41.692748,-527.165091,-635.447993,108.282901,...,2,False,False,0.615778,0.384222,-1.648521,0.150575,0.005914,0.000145,0
2025-11-12 20:45:00,101683.41,101716.61,101487.81,101539.01,114.583150,47.977011,38.913150,-493.315446,-607.021483,113.706038,...,3,False,False,0.497395,0.502605,-1.744016,0.631119,0.001340,-0.000707,0
2025-11-12 21:00:00,101539.01,101897.99,101520.41,101894.32,95.287950,63.965460,48.185714,-432.829422,-572.183071,139.353649,...,2,False,False,0.898643,0.101357,-1.359008,0.941019,0.005894,0.003885,0
2025-11-12 21:15:00,101894.32,101894.33,101694.00,101715.78,87.972500,53.964756,44.484238,-394.750065,-536.696470,141.946405,...,2,False,False,0.694525,0.305475,-1.485470,0.891229,0.002798,0.001710,0
2025-11-12 21:30:00,101715.78,101864.54,101715.66,101864.31,79.703270,60.179851,48.102269,-348.568687,-499.070913,150.502226,...,2,True,False,0.849814,0.150186,-1.285480,0.997649,0.001445,0.006991,0

In [8]:
df_1y['target'].value_counts()

target
 0    23010
 1     6265
-1     5917
Name: count, dtype: int64

In [9]:
export_df_1y = df_1y
export_df_5y = df_5y
export_df_10y = df_10y

%store export_df_1y
%store export_df_5y
%store export_df_10y

Stored 'export_df_1y' (DataFrame)
Stored 'export_df_5y' (DataFrame)
Stored 'export_df_10y' (DataFrame)

In [10]:
df_10y.tail(n=100)

,open,high,low,close,volume,rsi_6,rsi_12,macd,macd_signal,macd_hist,...,strong_bearish_signal,higher_lows_3,lower_highs_3,trend_strength_bullish,trend_strength_bearish,distance_from_sma_pct,candle_body_pct,momentum_5,momentum_10,target
timestamp,,,,,,,,,,,,,,,,,,,,,
2025-11-11 20:45:00,102829.77,102909.23,102658.36,102809.27,214.61049,29.128675,33.790598,-338.327177,-347.548217,9.221040,...,4,False,False,0.020417,0.979583,-1.275697,0.081716,-0.003729,-0.004900,0
2025-11-11 21:00:00,102809.27,103090.69,102659.17,102967.65,194.59036,42.780499,39.308317,-324.552097,-342.948993,18.396896,...,3,False,False,0.225729,0.774271,-1.084671,0.367028,-0.001539,-0.001865,0
2025-11-11 21:15:00,102967.65,103059.85,102769.23,102784.78,98.68881,33.767941,35.574061,-324.648977,-339.288990,14.640013,...,3,False,False,0.078747,0.921253,-1.215306,0.629241,-0.002283,-0.005960,0
2025-11-11 21:30:00,102784.78,102784.78,102476.09,102561.54,238.25717,25.804392,31.578897,-338.833496,-339.197891,0.364395,...,4,False,False,-0.054976,1.054976,-1.379595,0.723185,-0.003886,-0.005293,1
2025-11-11 21:45:00,102561.55,102836.20,102479.75,102633.92,265.41141,32.040058,34.192917,-340.311469,-339.420607,-0.890862,...,4,False,False,0.075758,0.924242,-1.258633,0.203030,-0.001905,-0.007538,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-11-12 20:30:00,101717.30,101846.15,101621.08,101683.41,173.97483,56.461330,41.692748,-527.165091,-635.447993,108.282901,...,2,False,False,0.615778,0.384222,-1.648521,0.150575,0.005914,0.000145,0
2025-11-12 20:45:00,101683.41,101716.61,101487.81,101539.01,114.58315,47.977011,38.913150,-493.315446,-607.021483,113.706038,...,3,False,False,0.497395,0.502605,-1.744016,0.631119,0.001340,-0.000707,0
2025-11-12 21:00:00,101539.01,101897.99,101520.41,101894.32,95.28795,63.965460,48.185714,-432.829422,-572.183071,139.353649,...,2,False,False,0.898643,0.101357,-1.359008,0.941019,0.005894,0.003885,0
2025-11-12 21:15:00,101894.32,101894.33,101694.00,101715.78,87.97250,53.964756,44.484238,-394.750065,-536.696470,141.946405,...,2,False,False,0.694525,0.305475,-1.485470,0.891229,0.002798,0.001710,0
2025-11-12 21:30:00,101715.78,101864.54,101715.66,101864.31,79.70327,60.179851,48.102269,-348.568687,-499.070913,150.502226,...,2,True,False,0.849814,0.150186,-1.285480,0.997649,0.001445,0.006991,0